import React, { useState } from 'react';
import { X, Share2, Copy, Check, Download, Link2 } from 'lucide-react';
import { useWorkspace } from '../context/WorkspaceContext';

export const ShareModal: React.FC = () => {
  const { activeModal, closeModal, activeConversation, selectedModel } = useWorkspace();
  const [copiedLink, setCopiedLink] = useState(false);

  if (activeModal !== 'share') return null;

  const shareUrl = `https://darkano.ai/share/${activeConversation?.id || 'session'}`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!activeConversation) return;
    let md = `# ${activeConversation.title}\n`;
    md += `*Generated by Darkano AI (${selectedModel.name}) on ${new Date(activeConversation.updatedAt).toLocaleString()}*\n\n`;

    activeConversation.messages.forEach(msg => {
      const author = msg.role === 'user' ? 'User' : `Darkano AI (${msg.modelId || selectedModel.name})`;
      md += `### ${author} [${msg.timestamp}]\n\n${msg.content}\n\n---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeConversation.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-md select-none">
      <div className="w-full max-w-md bg-[#0c0307]/95 rounded-2xl border border-rose-950/60 p-6 space-y-5 shadow-2xl animate-in zoom-in-95 duration-150 text-slate-200">
        <div className="flex items-center justify-between border-b border-rose-950/40 pb-3">
          <div className="flex items-center gap-2">
            <Share2 className="w-4 h-4 text-rose-400" />
            <h3 className="text-sm font-bold text-white tracking-tight">Share Conversation</h3>
          </div>
          <button
            onClick={closeModal}
            className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-white/5"
            id="share-modal-close-btn"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div>
          <div className="text-xs font-semibold text-white mb-1">
            {activeConversation?.title || 'Current Conversation'}
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Generate a read-only snapshot or download the transcript as clean Markdown.
          </p>
        </div>

        {/* Link input */}
        <div className="flex items-center gap-2">
          <div className="flex-1 flex items-center gap-2 px-3 py-2 rounded-xl bg-black/50 border border-rose-950/60 text-xs font-mono text-slate-300 truncate">
            <Link2 className="w-3.5 h-3.5 text-rose-400 shrink-0" />
            <span className="truncate">{shareUrl}</span>
          </div>
          <button
            onClick={handleCopyLink}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-gradient-to-r from-rose-800 to-rose-600 hover:from-rose-700 hover:to-rose-500 text-white font-semibold text-xs transition-all shrink-0 cursor-pointer shadow-sm"
            id="copy-share-link-btn"
          >
            {copiedLink ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedLink ? 'Copied' : 'Copy'}</span>
          </button>
        </div>

        {/* Download markdown export */}
        <div className="pt-2 border-t border-rose-950/40 flex items-center justify-between">
          <span className="text-xs text-slate-400">Offline Transcript:</span>
          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/5 hover:bg-rose-950/40 text-slate-200 border border-rose-950/60 hover:border-rose-800/50 text-xs transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-rose-400" />
            <span>Export Markdown (.md)</span>
          </button>
        </div>
      </div>
    </div>
  );
};
